sandbox_mode = "workspace-write"
approval_policy = "never"
additional_directories = ["/Users/pde/src/github.com/pdehlke/homie-dashboard"]


[sandbox_workspace_write]
writable_roots = [
	"/Users/pde/src/github.com/pdehlke/homeassistant/.git",
	"/Users/pde/src/github.com/pdehlke/homie-dashboard",
	"/Users/pde/src/github.com/pdehlke/homie-dashboard/.git",
	"/Users/pde/src/github.com/pdehlke/homeassistant/.codex",
	"/Users/pde/src/github.com/pdehlke/homie-dashboard/.codex",
]
